rm(list = ls())
pacman::p_unload(pacman::p_loaded())

pacman::p_load(tidyverse, ggsci)

set.seed(4)
class1 <- rnorm(100, 0, 1)
class2 <- rnorm(100, 5, sd = 0.5)
class3 <- rnorm(100, 3, sd= 0.3)

f <- function(x, mean, sd){
  (1/3)*dnorm(x, mean, sd)
}

data.frame(x = c(class1, class2, class3)) |>
  ggplot(aes(x = x)) +
  geom_histogram(aes(y=..density..), color = "black", fill = "transparent") +
  geom_function(fun = f, args = list(mean = 0, sd = 1), color = "red", linewidth = 1) +
  geom_function(fun = f, args = list(mean = 3, sd = 0.3), color = "forestgreen", linewidth = 1) +
  geom_function(fun = f, args = list(mean = 5, sd = 0.5), color = "blue", linewidth = 1) +
  theme_bw() +
  labs(y = "Density", x = "", title = "The data is generated by a mixture of three normal distributions") +
  theme(plot.title = element_text(size = 18))

